name: GetMoarFediverse

on:
  # uncomment the following 2 lines so that it runs automatically every 15 minutes
  # schedule:
  #   - cron: '*/15 * * * *'
  workflow_dispatch:

jobs:
  moar:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: g3rv4/GetMoarFediverse@main
        with:
          config_file: ${{ github.workspace }}/config.json
          api_key: ${{ secrets.FAKERELAY_APIKEY }}
